### PR TITLE
Zoom image

### PR DESCRIPTION
**Pull request by davidpmccormick**
Part of #8486

## Who is this for?
People who want to be able to zoom images to fill their viewport

## What is it doing for them?
Putting that functionality behind a toggle

Screenshot 2022-10-06 at 14 41 07

### CODE REVIEW

**Comment by davidpmccormick** [comment]
I'm now starting to think I can get away with only having one component that handles the open button and the modal window, which would remove the need for passing in the refs and remove the need for the MutationObserver. Going to put this back in draft and try that.

**Comment by melanierogan** [comment]
Having a look at the conflicts and trying to get this into stage/production

**Comment by melanierogan** [comment]
All working when toggle is turned on, example below:
Screenshot 2022-10-12 at 13 51 45

When you click the button it opens full viewport view of image, with an 'x' button to close/exit.

**Review by melanierogan — APPROVED** [review]
I've fixed the merge conflicts and run this branch locally to check functionality, all works well. Nice one David. I'll get this merged.

**Pull request merged**
