### PR TITLE
Fix padding of "Online" label in event cards

### PR DESCRIPTION
**Pull request by jamieparkinson**
Resolves https://github.com/wellcomecollection/wellcomecollection.org/issues/6529

image

### CODE REVIEW

**Comment by davidpmccormick** [comment]
I'm not sure about this. The negative margin on the `LabelsList` is there to override the bottom margin that necessarily exists on all individual `Label`s (so that they're not flush if they wrap onto two rows). The net result is no space, I think.

**Comment by jamieparkinson** [comment]
Hmm, that makes sense but the overlap is apparent in dev tools at least:
image

**Review by jamesgorrie — APPROVED** [review]

**Comment by davidpmccormick** [comment]
Is that overlap when the text is selected the result of the webfont vertical metrics being quite baggy? If you change the font-family to something from the system, I think it might look less odd.

**Comment by jamieparkinson** [comment]
Might be another one for some input from @GarethOrmerod

**Comment by GarethOrmerod** [comment]
I think moving over to Helvetica Regular has helped this vertical spacing. The online label looked a bit bunched up with the date & time below previously which would have been exacerbated by using Helvetica Light.

**Pull request closed without merging**
