### PR TITLE
Add new joiners to humans.txt

### PR DESCRIPTION
**Pull request by Amvla**
Added myself and Flora to Digital Platform section :)

### CODE REVIEW

**Review by georgiaewhitney — APPROVED** [review]
👋

**Review by rcantin-w — APPROVED** [review]
🙌

**Comment by rcantin-w** [comment]
Started running @Amvla through wc.org deployment steps, we'll continue on Monday and will merge this then :)

**Review by davidpmccormick — APPROVED** [review]
🎉

**Pull request merged**
