### PR TITLE
2. UID: Modify canonical URLs

### PR DESCRIPTION
**Pull request by rcantin-w**
## What does this change?

Part of #11073 

We want the canonical ref to be referencing the UID, not the ID.

## How to test

- Does it break any API Toolbar links to Prismic? (Should be using ID)
- Did I miss any? [See list](https://github.com/wellcomecollection/wellcomecollection.org/issues/11023)
- Does it work with and without `egWorks` on the guides pages, AND with and without the `Prismic staging` toggle as we need to check both legacy (Jason) and new (Kola Nut) guides are supported.

## How can we measure success?

UID becomes the main URLs, incl on Google results

## Have we considered potential risks?

Something breaks?

### CODE REVIEW

**Comment by gestchild** [comment]
If i match what's in this PR to the list you link to, I'm left with:

guides
projects
webcomics (deprecated)
webcomic-series (deprecated)

I think the webcomic things are covered by articles and series, but do the other two need doing?

**Comment by rcantin-w** [comment]
Good point! `guides` and `projects` are covered in `pages` here, the work should be covered [in this PR](https://github.com/wellcomecollection/wellcomecollection.org/pull/11148).

Splitting in smaller ones sometimes makes things more difficult to read through, but I thought it was slightly unrelated and ok to split since the current method very much ignores `projects` and `guides` and already sets their `pathname` as `/page/id`.

**Comment by rcantin-w** [comment]
> I think the webcomic things are covered by articles and series

That's also my understanding!

**Comment by gestchild** [comment]
Noticed while testing this that if I visit http://localhost:3000/exhibitions/ZZP8BxAAALeD00jo, then I see the Exhibition access content on the page:
Screenshot 2024-09-06 at 16 16 26

But if I go to http://localhost:3000/exhibitions/jason-and-the-adventure-of-254
 they vanish

**Comment by rcantin-w** [comment]
Great catch, thank you!
It was indeed due to the `uid` being used to fetch related documents, which I'd done [here](https://github.com/wellcomecollection/wellcomecollection.org/pull/11124/files#diff-b08f2382740ac04a09578955aaf7f352caded698869453d3dfc8a4ba8c13ba53R102) but obviously didn't do properly everywhere. I'll have to have a look at if it's missing from anywhere else!

[I just pushed the fix in the parent PR](https://github.com/wellcomecollection/wellcomecollection.org/pull/11124/commits/4c38f78a59cf8f1026ffc592300e35be26bdf19e) and will pull it into this branch shortly.

**Comment by gestchild** [comment]
Everything else seems to be working as expected

**Comment by rcantin-w** [comment]
I went through everything I could find and found that `event-series` and `seasons` also were fetching related things with uid! [Fix is here](https://github.com/wellcomecollection/wellcomecollection.org/pull/11124/commits/26f7e0816bbbf10ff2345dd44ce070d7ec40621c?diff=split&w=1).
I believe everything now explicitly uses a document's `id` for those.

**Review by gestchild — APPROVED** [review]

**Pull request merged**
