### PR TITLE
Playwright: Upgrade tsconfig node version and fix errors

### PR DESCRIPTION
**Pull request by rcantin-w**
## What does this change?

Noticed that there were imports of non-existing types and TS errors, so fixed that, as well as upgraded tsconfig to follow Node20 recommendations. 
Upgraded Typescript package, too.

Moved from `ts-node` to `tsx` as I had to do [in another upgrade PR](https://github.com/wellcomecollection/wellcomecollection.org/pull/11003) and as[ recommended by others](https://stackoverflow.com/questions/62096269/cant-run-my-node-js-typescript-project-typeerror-err-unknown-file-extension/76343394#76343394).

Added  playwright's `yarn tsc` to the Typescript GitHub action.

## How to test

1. Do the e2e tests run fine?
2. Locally, if you `cd playwright`, `yarn && yarn tsc`, does it error?

## How can we measure success?

Up to date!

## Have we considered potential risks?
N/A

### CODE REVIEW

**Review by georgiaewhitney — DISMISSED** [review]
Needed to do a `yarn playwright install` on top of ye olde `yarn`, but all 68 tests passing for me ✨

**Comment by rcantin-w** [comment]
I've added a step to the Typescript action that also runs through Playwright so the TS errors can get caught in the future.

**Comment by rcantin-w** [comment]
Made more changes so asking for another round of reviews.

**Review by georgiaewhitney — APPROVED** [review]
Re-ran steps after fresh pull of changes, `yarn && yarn tsc` working and passing tests for me ✅
Screenshot 2024-08-14 at 16 31 15

**Pull request merged**
