### PR TITLE
Only run Lighthouse for a couple of pages in PRs

### PR DESCRIPTION
**Pull request by jamieparkinson**
It takes ages

### CODE REVIEW

**Review by jamesgorrie — APPROVED** [review]
Homepage maybe?

**Comment by jamieparkinson** [comment]
Yeah, probably more useful than What's On tbh

**Comment by alexwlchan** [comment]
At least for me, the reduced diff is no more helpful than before – I'm not going to notice if those numbers move without a delta.

**Comment by jamieparkinson** [comment]
A delta is quite tricky to do and is likely to be _very_ slow, but what we can add next is thresholds upon which it'll fail or warn - I think that's what we should do next rather than getting rid of it

**Pull request merged**
