### PR TITLE
Use relative path to prefix module

### PR DESCRIPTION
**Pull request by ajrussellaudio**

### CODE REVIEW

**Review by jamesgorrie — APPROVED** [review]

**Comment by jamesgorrie** [comment]
Seen this quite a lot with VS code - if that's what you're using. Might try find some time to see if it's our setup that's the issue.

**Comment by ajrussellaudio** [comment]
Thanks @jamesgorrie I'll have a look as well. I was thinking it has something to do with webpack aliases, but I don't know what makes VS Code think they're a thing.

**Comment by jamesgorrie** [comment]
That or the workspaces potentially... more 🔍 needed.

**Comment by ajrussellaudio** [comment]
This pref seems to make VS Code behave how we want:

```json
  "typescript.preferences.importModuleSpecifier": "relative"
```

It's not a long-term fix but it should prevent another goof like this ☝️

**Pull request merged**
