### PR TITLE
bump lambda versions

### PR DESCRIPTION
**Pull request by jamesgorrie**
🎸

### CODE REVIEW

**Comment by jamesgorrie** [comment]
Applied and checked

**Comment by gestchild** [comment]
thank you

**Comment by kenoir** [comment]
What change does this release?

**Comment by gestchild** [comment]
it's for this: https://github.com/wellcomecollection/wellcomecollection.org/pull/5942

**Comment by jamesgorrie** [comment]
Perhaps it should be practice to release with the PR?

**Pull request merged**
