### PR TITLE
Remove some more unused code

### PR DESCRIPTION
**Pull request by alexwlchan**

### CODE REVIEW

**Review by davidpmccormick — APPROVED** [review]
I'm really enjoying this spring(/autumn) cleaning. Curious to know how you're determining what can be removed?

**Comment by alexwlchan** [comment]
> Curious to know how you're determining what can be removed?

Gradually reading through the codebase and running "find all" to see how things are being used.

**Comment by davidpmccormick** [comment]
Nice. I thought that would have to be what it was, glad/a bit sad I'm not missing out on some magic find-export-that-isn't-imported-anywhere thing.

**Comment by alexwlchan** [comment]
Sadly not. I did have a script that walked the codebase and opened every file that looked for things like names that didn't appear to be used anywhere (look for a line starting `export const`, split on spaces, take the third word) sort of thing, but it's pretty crude and I had to check everything it suggested first.

**Comment by jamieparkinson** [comment]
@davidpmccormick @alexwlchan fwiw, IntelliJ's "unused declaration" inspection is pretty good at this (not infallible, but better than nothing)

**Pull request merged**
