### PR TITLE
Overview page should set link to search context

### PR DESCRIPTION
**Pull request by AMBacelar**
## Who is this for?
Users of the overview page when searching should be able to return back to the search page when they click on a work.

now, the question is if I should expand this logic and feature to stories pages?

## What is it doing for them?
simply ensuring the search result page (Overview) updates the SearchContext was enough for the stories page to acknowledge that there was a search happening.

### CODE REVIEW

**Comment by rcantin-w** [comment]
> now, the question is if I should expand this logic and feature to stories pages?

one for @jtweed or @jennpb ? 👀

**Comment by rcantin-w** [comment]
Another question: Should we make it work for filters as well? It currently only works if there is a query, but if someone uses filters without a query (which might not be a thing, again, I'm just asking), it doesn't offer a Back to results link.

**Comment by jtweed** [comment]
I'd vote for not doing for stories, as search isn't a primary journey for stories in the same way as it is for works and we don't have the design support right now to integrate the link into the header without it being distracting.

However it should work if there are applied filters, not just if there is a full text query.

**Review by rcantin-w — DISMISSED** [review]
Adapt to support filters only queries

**Review by rcantin-w — APPROVED** [review]

**Pull request merged**
