### PR TITLE
Add a reset-all button for toggles

### PR DESCRIPTION
**Pull request by jamieparkinson**
I've noticed a few times recently that stale toggle state has caused perceived bugs for some people (myself included!). Of course we can/do check in an Incognito window but thought it would be convenient to have a button to do it for us. It looks like this:

image

### CODE REVIEW

**Review by jamesgorrie — APPROVED** [review]

**Review by jamesgorrie — COMMENTED** [review]
could just bin the cookies instead of setting them, which might override the default value if it changes.

**Comment by jamieparkinson** [comment]
Good point, will do that

**Comment by davidpmccormick** [comment]
When I'm king you'll need a license to use emoji

**Comment by jamieparkinson** [comment]
👑 📝 💯

**Comment by davidpmccormick** [comment]
slightly smiling face

**Pull request merged**
