### PR TITLE
Promote the latest serials on the stories page

### PR DESCRIPTION
**Pull request by davidpmccormick**
Part of #6647, probably supersedes #7643

- [ ] Needs content team input for the section heading to explain what serials are (placeholder copy added in this PR).

image

### CODE REVIEW

**Comment by alexwlchan** [comment]
Possibly obvious question, but have we told the Editorial team we're about to make this change?

**Comment by davidpmccormick** [comment]
> Possibly obvious question, but have we told the Editorial team we're about to make this change?

Have brought it up in `#wc-editorial`

**Comment by dannybirchall** [comment]
@davidpmccormick @alexwlchan I've got some thoughts about how we might do this (they're in the editorial Slack) -- is it still possible to have a conversation about it?

**Comment by alexwlchan** [comment]
Closing in favour of #8398.

**Pull request closed without merging**
