### PR TITLE
Add comments to explain quote/quotev2 and add a TODO

### PR DESCRIPTION
**Pull request by rcantin-w**
## Who is this for?
Future devs

## What is it doing for them?
Explains the gist of what I found out when working on #9925 and possibly helps future devs navigate these specific slices.
Added a wishful to do for one day when we have time on our hands or figure out how to automate this migration with Prismic.

### CODE REVIEW

**Comment by alexwlchan** [comment]
I wonder – do we know if it's possible to rename slices in Prismic? Will we ever be able to rename QuoteV2 to Quote?

And if not, should we really make Quote the canonical type, and migrate in the other direction?

**Comment by rcantin-w** [comment]
> I wonder – do we know if it's possible to rename slices in Prismic? Will we ever be able to rename QuoteV2 to Quote?
> And if not, should we really make Quote the canonical type, and migrate in the other direction?

I wondered about the latter as it seems silly to go one way and then revert, but I actually don't really know the answer to the first question. I know we've updated them _on the UI_ but I have to assume the reason it's still V2 it's because it's actually not possible, so it's a good point.

It just means we'd have to manually migrate 589 instances the other way, so even less interesting without an automated tool.

**Comment by rcantin-w** [comment]
@alexwlchan I could add a reference to [this comment](https://github.com/wellcomecollection/wellcomecollection.org/pull/9979#issuecomment-1602448601) in the comment? Very meta!

**Comment by alexwlchan** [comment]
Yeah, why not :D

**Review by alexwlchan — APPROVED** [review]

**Pull request merged**
