### PR TITLE
remove catalogue from deploy_all_apps script

### PR DESCRIPTION
**Pull request by agnesgaroux**
## Who is this for?
Stage deployment pipeline

## What is it doing for them?
This issue: https://github.com/wellcomecollection/wellcomecollection.org/issues/10168
Terraform was applied but the changes to the deployment pipeline were not
https://github.com/wellcomecollection/wellcomecollection.org/pull/10169/files

### CODE REVIEW

**Comment by kenoir** [comment]
👌 , on the way, I think you might need the other `.buildkite` folder changes in https://github.com/wellcomecollection/wellcomecollection.org/pull/10169/files.

**Review by kenoir — APPROVED** [review]

**Comment by kenoir** [comment]
Oop, and this one too: https://github.com/wellcomecollection/wellcomecollection.org/pull/10169/files#diff-c92a380d4817f07e3393f8f6419206a3a05774f51fc67b71f2e51a03f60096caR12

**Comment by kenoir** [comment]
I've put the changes in a PR: https://github.com/wellcomecollection/wellcomecollection.org/pull/10517 so they can get merged into here, before main if that's useful.

**Comment by agnesgaroux** [comment]
I put it in commits on this branch directly

**Pull request merged**
