### PR TITLE
Remove a bunch of utility classes that we aren't using

### PR DESCRIPTION
**Pull request by alexwlchan**
## Who is this for?

Devs.

## What is it doing for them?

Keeping the codebase clean by removing some unused classes. I searched the codebase for all these classes; if they weren't used I removed them. Most of them are pretty simple and would fall under the axe of #8420 anyway.

(I’m trying to work out how something works on the Stories homepage, so I’ve been reading the rendered CSS. I spotted some unused classes as part of that. :D)

### CODE REVIEW

**Comment by alexwlchan** [comment]
Closing; this seems to have broken something in the footer – the social media icons have gone from green to white for non-obvious reasons, and I don't care to debug further.

**Comment by alexwlchan** [comment]
Reopening; it looks fine if I stop and then restart `yarn content`. Maybe there's a bug where the regenerated styles aren't working properly with live reload?

**Comment by rcantin-w** [comment]
[I've had this before](https://github.com/wellcomecollection/wellcomecollection.org/pull/8408#discussion_r965048695) where the insertion order seemed to compile a bit differently. Only affected the footer too, but to be fair the icon styles need refactoring in that the way they're styled in the footer is overcomplicated. Good thing we're moving the icons to white soon 😄

**Review by rcantin-w — APPROVED** [review]
Double checked and it seems good, thanks for cleaning up!

**Pull request merged**
