### PR TITLE
Tracking sourcePath

### PR DESCRIPTION
**Pull request by gestchild**
relates to #10650

adds the sourcePath value to more links

### CODE REVIEW

**Comment by taceybadgerbrook** [comment]
🎆

**Comment by taceybadgerbrook** [comment]
@gestchild I'm testing this out.

When I go from [this concepts page](https://wellcomecollection.org/concepts/ztbtp7ta) to [this works page](https://wellcomecollection.org/works/a32wamxr), there is no page.query.sourcePath field in Kibana.

When I go from the same concepts page to [this image modal](https://wellcomecollection.org/concepts/ztbtp7ta#b3mfrdne), page.query.sourcePath is populated with, "/works/a32wamxr" which is the works page I viewed first.

**Comment by taceybadgerbrook** [comment]
@gestchild  If is was a Kibana mapping issue, would this mean I would see, "/concepts/ztbtp7ta" in another field? Here's what I see when I look at Kibana Discover after I view the same concept page and go to the works page:

image

**Comment by gestchild** [comment]
I'm not very familiar with Kibana, but we can sit together tomorrow and try and work it out

**Pull request merged**
