### PR TITLE
Pixels for downloads

### LINKED ISSUE #5196: Making image size visible to downloaders
# What is it and who's it for?
Researching using the digitised collections

# Problem to solve
Showing the size of downloadable images

UV implementation describes image size in pixels, so we know this data is available via the IIIF manifest:
Screenshot 2020-03-25 at 10 38 55

A more useful representation of size could be file size, as some users might not understand pixels, though we'd probably need a bit more research to find out what is preferable.

# User story
In order to reuse or download an image that meets the specs of my output
As a researcher
I want to know how big an image is.

## Background research
https://wellcomecloud.sharepoint.com/:p:/s/wcdigitalexperience/ET_fRUahU_lNmsmE0cOZ0lMBIDWA7wOWDOaXXs3n9B3PTg?e=yz9rvx (slide 16+)

3 users want to know the download size of the both images in MB (rather than px)​
2 users state the download size can be known by downloading the image​
2 users talk about a blog that they write​
1 user doesn't know what 'px' means

Quotes:
"I'd assume full size is better quality"​
"It's nice to have size option; [for a] blog post [it] needs to be smaller due to server space and having post load faster "​
"Sometimes I'm limited re size"​
"If I use for the background it need to be bigger than 760px"​
"I usually download full size and then I might resize to the dimension and size and need/want"​
"One would imagine you wouldn't have made something smaller by only a few pixels"

## Acceptance criteria

# Implementation 

## Testing and tracking
- Have you talked to Tacey?
- Test plan
- Will you need to set up additional tracking?
- What is the expected life span for tracking?

## Measurement
- Related KPIs (e.g. breadth of collection accessed, reading time, etc.)

## Other considerations 
<---Delete as appropriate--->
- Impact on URL design
- Cardigan documentation

### PR DESCRIPTION
**Pull request by gestchild**
Fixes #5196

## Who is this for?
Researching using the digitised collections

## What is it doing for them?
Showing the size of downloadable images

Screenshot 2020-03-25 at 17 19 25

### CODE REVIEW

**Comment by jennpb** [comment]
Just a few stylistic tweaks from me:

- remove extra spacing between pixel dimensions
- remove 'full size'
- Put PDF third in list
- change label on PDF so it says `Whole item` (allow file format to be styled in same way as JPG


`This image (0000x0000 pixels) JPG`

`This image (760x1000 pixels) JPG`

`Whole item PDF`

**Comment by gestchild** [comment]
Screenshot 2020-03-26 at 16 45 16

**Comment by GarethOrmerod** [comment]
Some suggestions from me from having a quick look around. I think the image sizes are easier to read with the space but I've uploaded a version without too.

Download menu

**Comment by jennpb** [comment]
On Friday I asked Holly to have a look at this to sense-check, as someone who handles image-size related calls to the Digital Production team. Can we hold off til she gets back to me, please?

**Pull request merged**
