### PR TITLE
Google tag manager

### PR DESCRIPTION
**Pull request by gestchild**
Relates to #8524

This removes the Google Analytics (gtag) code relating to GA4 and adds Google Tag Manager. The GA4 tag will then be implemented from within Google Tag Manager instead. I've added a bare bones GA4 tag in our Google Tag Manager account, but would need @taceybadgerbrook to look at this and add any parameters or custom properties we want configured.

N.B. in code we had configured page_path and cookie_flags.

     window.gtag('config', GOOGLE_ANALYTICS_V4_ID, {
        page_path: path,
        cookie_flags: 'SameSite=None;secure',
      });

~I've also moved the instantiation of the dataLayer outside of the the Universal Analytics code, as it will be used by Google Tag Manager, otherwise the Universal Analytics code remains untouched.~

I've also taken out the instantiation of the dataLayer from Universal Analytics code. This is taken care of by GTM.

### CODE REVIEW

**Review by rcantin-w — COMMENTED** [review]
For my own learnings, what's the difference between `GoogleTagManager` and `GoogleTagManagerNoScript` (s the former "better" in a way we don't want to just use the latter?)

**Comment by taceybadgerbrook** [comment]
@gestchild I have no comments on the GA4 tag. If you are linking to the existing GA4 property, then all should be fine.

**Comment by gestchild** [comment]
@rcantin-w , the noscript version is a less functional fallback for users who visit the website with javascript disabled. I put it in because that's what the installation instructions recommend. But your question has me questioning whether it is actually worth including it.

**Comment by rcantin-w** [comment]
> But your question has me questioning whether it is actually worth including it. 

If it's a case of "better than nothing", it is probably worth it!

**Review by rcantin-w — APPROVED** [review]

**Comment by gestchild** [comment]
> @gestchild I have no comments on the GA4 tag. If you are linking to the existing GA4 property, then all should be fine.

Yes, I'm using the same one. I just wasn't sure about needing to configure the cookie_flags, we [did this explicitly](https://github.com/wellcomecollection/wellcomecollection.org/pull/7514) because of #7503. Are you confident we don't need to do this in GTM somewhere?

**Comment by gestchild** [comment]
Screenshot 2023-01-31 at 14 40 13

I had to add a 'cookie_flags' field with a value of 'SameSite=None;secure' in GTM for the cookies secure and same site values to be added as they had been previously.

**Comment by gestchild** [comment]
Triggered deploy to prod @ (01/02/2023 10:41) - will keep an eye on UA and GA4

**Pull request merged**
