### PR TITLE
Check we're actually formatting months correctly

### PR DESCRIPTION
**Pull request by alexwlchan**
UTC months are 0-indexed, not 1-indexed.  This was causing requests to be placed for the previous month. Tentative fix for https://github.com/wellcomecollection/wellcomecollection.org/issues/8457

I'm on a train; I don't have reliable enough Internet to test properly, but even if this isn't the whole issue it's definitely wrong.

## Who is this for?

People requesting items.

## What is it doing for them?

Making sure requests are placed for the right month.

### CODE REVIEW

**Review by rcantin-w — APPROVED** [review]
Tried to test a few more edge cases (end/start of year) and it looks good. There are other `formatDate` type functions in `common/format-dates.ts`, could be good to align/put in the same place?

**Comment by alexwlchan** [comment]
> Tried to test a few more edge cases (end/start of year) and it looks good.

Good suggestion, I've added a couple more too – I got bitten by a bug with date formatting on 1 January last year.

> There are other formatDate type functions in common/format-dates.ts, could be good to align/put in the same place?

Yeah, I'm not sure on that. There's definitely some value in keeping them together, but we've also had issues with functions being used beyond their initial scope. I'm going to leave it as-is for now, but maybe I'll change my mind later.

**Comment by rcantin-w** [comment]
I used to work on subscription boxes... Timezones and dates I'm always paranoid about, so always good to do edge case stuff 😅 

I think if we keep them separate, then comments are always good to have! The other `formatDate` has a different format (day month year), so it does serve a different purpose.

**Comment by davidpmccormick** [comment]
Why would UTC months be zero-indexed by UTC dates be one-indexed? Like this stuff wasn't hard enough already.

**Pull request merged**
