### PR TITLE
increase timeout on findByText

### PR DESCRIPTION
**Pull request by gestchild**
Hoping that this fixes the failing tests

### CODE REVIEW

**Review by davidpmccormick — APPROVED** [review]
🤞

**Review by jamesgorrie — COMMENTED** [review]
This feels a bit iffy - as we're saying that we're okay with 5 second response times?

**Comment by gestchild** [comment]
> This feels a bit iffy - as we're saying that we're okay with 5 second response times?

Jest uses jsdom to simulate the DOM environment, so not sure how reliable it is as a test of performance, we're really only testing that what we expect to happen is happening

**Comment by gestchild** [comment]
doesn't look like it worked anyway

**Pull request closed without merging**
