### PR TITLE
Enforce button types

### PR DESCRIPTION
**Pull request by davidpmccormick**
Using an enum string prop, enforces the type of button ('primary' | 'secondary' | 'tertiary') or control ('light' | 'dark'), rather than relying on the `extraClasses` prop.

### CODE REVIEW

**Comment by jamesgorrie** [comment]
@davidpmccormick ☝️❓

**Comment by davidpmccormick** [comment]
I think I stopped here (rather than getting as far as e.g. `PrimaryButton`, `SecondaryButton`), because of complications(/duplication) involved in passing down props. But I'm not averse to the idea of turning them into their own components, as long as it isn't at the expense of being able to develop with them without a passing-props-around headache.

I think this is good enough for now?

**Comment by jamesgorrie** [comment]
> I think this is good enough for now?

Yea, it's more the conversation about create a more pure API from the design system where we do the heavy lifting in the components. Once the props are passed once - we never do it again, so it's not really an expense.

**Comment by davidpmccormick** [comment]
On the flip-side, changing the props once turns into changing the props as many times as we have buttons.

**Comment by jamesgorrie** [comment]
Ah, I see what you mean, if we change the props on the root `Button` component.
True.

**Pull request merged**
