### PR TITLE
Make gaDimensions available in the dataLayer

### PR DESCRIPTION
**Pull request by davidpmccormick**
## Who is this for?
Data analysts

## What is it doing for them?
Adding custom dimension information into the dataLayer

This was information that we had access to before we moved to GA4. Seems like we no longer sent it anywhere after the switch over.

This was specifically for getting the `partOf` information (e.g. when an article is part of a series). The change also required a change in how we query that information in GTM.

@taceybadgerbrook when this goes in you should be able to see an array of ids indicating which (if any) series an article is part of

### CODE REVIEW

**Review by rcantin-w — APPROVED** [review]

**Comment by taceybadgerbrook** [comment]
When I try and Preview the tag, "GA4 - series/serial - pageview," I see this after clicking on [this story](https://wellcomecollection.org/series/ZS5vzRIAACcAM_SF) which is part of a series:
image

**Comment by taceybadgerbrook** [comment]
When I removed partOf as an event parameter, the tag fires fine.

**Comment by davidpmccormick** [comment]
The [page you've linked to](https://wellcomecollection.org/series/ZS5vzRIAACcAM_SF) is the index page for the Beauty Boardroom series, so it _itself_ isn't part of anything. If you visit one of the individual comics in the list on that page (e.g. [Crisis meeting](https://wellcomecollection.org/articles/ZS53KBIAACkANBX3)) you should see the `partOf` array will then contain the id for the Beauty Boardroom series (ZS5vzRIAACcAM_SF).

Is that what you're after?

image

**Comment by taceybadgerbrook** [comment]
@davidpmccormick Well the data is definitely coming through so it's a case of me figuring out where I'm preventing it (ie being too clever by half.) Fingers crossed I can sort this.

image

**Comment by taceybadgerbrook** [comment]
@davidpmccormick Cracked it!
image

**Pull request merged**
